apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: kotlin
            - name: POSTGRES_PASSWORD
              value: example
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-db
